version: "3"

services:
  money-pit-api:
    build:
      context: .
      dockerfile: Dockerfile.Build
    container_name: money-pit
    image: money-pit
    env_file:
      - ./.env
    environment:
      - MONGO_URL=mongodb://host.docker.internal:27017/MoneyPit
      - LOCAL=false
    volumes:
      - ./src:/usr/app/src
      - ./logs:/logs
      - /usr/src/app/node_modules

    networks:
      - app-network
    ports:
      - "3000:3000"
      - "27017:27017"

networks:
  app-network:
    driver: bridge
